import { ContentComponentType } from '../enums';
import { BackgroundPosition } from '../enums/background-position.enum';
import { DateFormat } from '../enums/date-format.enum';
import { EventColumnType, EventType } from '../enums/event-type.enum';
import { HeadingType } from '../enums/heading-type.enums';
import { SiteAction } from '../enums/site-action.enum';
import { uuidv4 } from '../utils/uuid';
import { ILayout, IRow } from './layout-schema.interface';

export const exampleLayout: ILayout = {
  body: {
    id: uuidv4(),
    type: ContentComponentType.BODY,
    rows: [
      {
        id: uuidv4(),
        type: ContentComponentType.BLOCK,
        columns: [
          {
            id: uuidv4(),
            type: ContentComponentType.COLUMN,
            width: 1,
            contents: [
              {
                id: uuidv4(),
                type: ContentComponentType.MENU,
                values: {
                  menuItems: [
                    {
                      id: uuidv4(),
                      text: 'Just text',
                      href: '',
                      name: '',
                      target: '_self',
                      actionType: SiteAction.WEBSITE,
                    },
                    {
                      id: uuidv4(),
                      text: 'Link text',
                      href: 'https://telex.hu',
                      name: '',
                      target: '_self',
                      actionType: SiteAction.WEBSITE,
                    },
                    {
                      id: uuidv4(),
                      text: 'Just text again',
                      href: '',
                      name: '',
                      target: '_self',
                      actionType: SiteAction.WEBSITE,
                    },
                  ],
                  fontSize: 16,
                  fontFamily: 'Arial',
                  fontWeight: 'Regular',
                  linkColor: '#5c5c5c',
                  textColor: '#2c2c2c',
                  layout: 'horizontal',
                  separator: '|',
                  textAlign: 'right',
                  paddingTop: 10,
                  paddingBottom: 10,
                  paddingRight: 10,
                  paddingLeft: 10,
                  containerPadding: {
                    paddingTop: 10,
                    paddingBottom: 10,
                    paddingRight: 10,
                    paddingLeft: 10,
                  },
                  locked: false,
                },
              },
            ],
            values: {},
          },
          {
            id: uuidv4(),
            type: ContentComponentType.COLUMN,
            width: 1,
            contents: [
              {
                id: uuidv4(),
                type: ContentComponentType.TEXT,
                values: {
                  text: '<p>Lorem ipsum dolor imet</p>',
                  fontFamily: 'Arial',
                  fontWeight: 'Regular',
                  fontSize: 14,
                  textColor: '#61a71b',
                  textAlign: 'center',
                  lineHeight: 120,
                  inheritBodyStyles: true,
                  linkColor: '#3aaee0',
                  underline: false,
                  containerPadding: {
                    paddingBottom: 10,
                    paddingTop: 10,
                    paddingLeft: 10,
                    paddingRight: 10,
                  },
                  displayConditions: [
                    EventType.Video,
                    EventType.Normal,
                  ],
                  locked: false,
                },
              },
            ],
            values: {},
          },
        ],
        values: {
          locked: false,
          contentBackgroundColor: '#ffffff',
        },
      },
      {
        id: uuidv4(),
        type: ContentComponentType.BLOCK,
        columns: [
          {
            id: uuidv4(),
            type: ContentComponentType.COLUMN,
            width: 1,
            contents: [
              {
                id: uuidv4(),
                type: ContentComponentType.EVENT,
                values: {
                  eventColumnType: EventColumnType.Type1,
                  textColor: '#000000',
                  lineHeight: 130,
                  textAlign: 'left',
                  locked: false,
                  eventRows: [
                    {
                      id: uuidv4(),
                      type: ContentComponentType.BLOCK,
                      columns: [
                        {
                          id: uuidv4(),
                          type: ContentComponentType.COLUMN,
                          width: 1,
                          contents: [
                            {
                              id: uuidv4(),
                              type: ContentComponentType.IMAGE,
                              values: {
                                src: 'http://placekitten.com/200/300?image=1',
                                textAlign: 'center',
                                width: '50',
                                paddingTop: 10,
                                paddingLeft: 10,
                                paddingBottom: 10,
                                paddingRight: 10,
                                action: SiteAction.WEBSITE,
                                altText: 'Cat',
                                href: 'https://ext.stx.interticket.com/',
                                target: '_blank',
                                locked: false,
                              },
                            },
                          ],
                          values: {},
                        },
                        {
                          id: uuidv4(),
                          type: ContentComponentType.COLUMN,
                          width: 2,
                          contents: [

                          ],
                          values: {},
                        },
                      ],
                      values: {
                        locked: false,
                        contentBackgroundColor: '#ffffff',
                      },
                    },
                  ],
                  ticketTopRows: [
                    {
                      id: uuidv4(),
                      type: ContentComponentType.BLOCK,
                      columns: [
                        {
                          id: uuidv4(),
                          type: ContentComponentType.COLUMN,
                          width: 1,
                          contents: [
                            {
                              id: uuidv4(),
                              type: ContentComponentType.TEXT,
                              values: {
                                text: '<p>Tickets</p>',
                                fontFamily: 'Arial',
                                fontWeight: 'Regular',
                                fontSize: 17,
                                textColor: '#a2d6f9',
                                textAlign: 'left',
                                lineHeight: 120,
                                inheritBodyStyles: true,
                                linkColor: '#3aaee0',
                                underline: false,
                                containerPadding: {
                                  paddingBottom: 0,
                                  paddingTop: 0,
                                  paddingLeft: 0,
                                  paddingRight: 0,
                                },
                                locked: false,
                              },
                            },
                          ],
                          values: {},
                        },
                      ],
                      values: {
                        locked: false,
                        contentBackgroundColor: '#ffffff',
                      },
                    },
                  ],
                  ticketTicketRows: [
                    {
                      id: uuidv4(),
                      type: ContentComponentType.BLOCK,
                      columns: [
                        {
                          id: uuidv4(),
                          type: ContentComponentType.COLUMN,
                          width: 1,
                          contents: [],
                          values: {},
                        },
                        {
                          id: uuidv4(),
                          type: ContentComponentType.COLUMN,
                          width: 1,
                          contents: [],
                          values: {},
                        },
                        {
                          id: uuidv4(),
                          type: ContentComponentType.COLUMN,
                          width: 1,
                          contents: [],
                          values: {},
                        },
                      ],
                      values: {
                        locked: false,
                        contentBackgroundColor: '#ffffff',
                      },
                    },
                  ],
                  ticketBottomRows: [
                    {
                      id: uuidv4(),
                      type: ContentComponentType.BLOCK,
                      columns: [
                        {
                          id: uuidv4(),
                          type: ContentComponentType.COLUMN,
                          width: 1,
                          contents: [
                            {
                              id: uuidv4(),
                              type: ContentComponentType.TEXT,
                              values: {
                                text: '<p>You can either print or show your tickets from you mobile.</p>',
                                fontFamily: 'Arial',
                                fontWeight: 'Regular',
                                fontSize: 13,
                                textColor: '#a2d6f9',
                                textAlign: 'left',
                                lineHeight: 120,
                                inheritBodyStyles: true,
                                linkColor: '#3aaee0',
                                underline: false,
                                containerPadding: {
                                  paddingBottom: 0,
                                  paddingTop: 0,
                                  paddingLeft: 0,
                                  paddingRight: 0,
                                },
                                locked: false,
                              },
                            },
                          ],
                          values: {},
                        },
                      ],
                      values: {
                        locked: false,
                        contentBackgroundColor: '#ffffff',
                      },
                    },
                  ],
                },
              },
            ],
            values: {},
          },
        ],
        values: {
          locked: false,
          contentBackgroundColor: '#ffffff',
        },
      },
      {
        id: uuidv4(),
        type: ContentComponentType.BLOCK,
        columns: [
          {
            id: uuidv4(),
            type: ContentComponentType.COLUMN,
            width: 1,
            contents: [
              {
                id: uuidv4(),
                type: ContentComponentType.IMAGE,
                values: {
                  src: 'http://placekitten.com/200/300?image=1',
                  textAlign: 'center',
                  width: '50',
                  paddingTop: 10,
                  paddingLeft: 10,
                  paddingBottom: 10,
                  paddingRight: 10,
                  action: SiteAction.WEBSITE,
                  altText: 'Cat',
                  href: 'https://ext.stx.interticket.com/',
                  target: '_blank',
                  locked: false,
                },
              },
            ],
            values: {},
          },
          {
            id: uuidv4(),
            type: ContentComponentType.COLUMN,
            width: 1,
            contents: [],
            values: {},
          },
          {
            id: uuidv4(),
            type: ContentComponentType.COLUMN,
            width: 1,
            contents: [
              {
                id: uuidv4(),
                type: ContentComponentType.BUTTON,
                values: {
                  textAlign: 'center',
                  paddingTop: 10,
                  paddingLeft: 10,
                  paddingBottom: 10,
                  paddingRight: 10,
                  action: SiteAction.WEBSITE,
                  href: 'https://ext.stx.interticket.com/',
                  target: '_blank',
                  borderTopLeftRadius: 10,
                  borderTopRightRadius: 10,
                  borderBottomLeftRadius: 10,
                  borderBottomRightRadius: 10,
                  borderTopWidth: 1,
                  borderRightWidth: 1,
                  borderBottomWidth: 1,
                  borderLeftWidth: 1,
                  borderTopStyle: 'solid',
                  borderRightStyle: 'solid',
                  borderBottomStyle: 'solid',
                  borderLeftStyle: 'solid',
                  borderTopColor: '#000',
                  borderRightColor: '#000',
                  borderBottomColor: '#000',
                  borderLeftColor: '#000',
                  textColor: '#fff',
                  backgroundColor: '#3AAEE0',
                  text: '<p>Go to website</p>',
                  width: '100',
                  autoWidth: true,
                  fontSize: 16,
                  fontFamily: 'Arial',
                  lineHeight: 150,
                  fontWeight: 'Bold',
                  containerPadding: {
                    paddingBottom: 10,
                    paddingTop: 10,
                    paddingLeft: 10,
                    paddingRight: 10,
                  },
                  locked: false,
                },
              },
            ],
            values: {},
          },
        ],
        values: {
          locked: false,
          contentBackgroundColor: '#ffffff',
        },
      },
      {
        id: uuidv4(),
        type: ContentComponentType.BLOCK,
        columns: [
          {
            id: uuidv4(),
            type: ContentComponentType.COLUMN,
            width: 1,
            contents: [
              {
                id: uuidv4(),
                type: ContentComponentType.DIVIDER,
                values: {
                  width: 70,
                  textAlign: 'center',
                  borderTopColor: '#000000',
                  borderTopStyle: 'dashed',
                  borderTopWidth: 2,
                  locked: false,
                },
              },
            ],
            values: {},
          },
          {
            id: uuidv4(),
            type: ContentComponentType.COLUMN,
            width: 1,
            contents: [],
            values: {},
          },
          {
            id: uuidv4(),
            type: ContentComponentType.COLUMN,
            width: 1,
            contents: [],
            values: {},
          },
          {
            id: uuidv4(),
            type: ContentComponentType.COLUMN,
            width: 1,
            contents: [],
            values: {},
          },
        ],
        values: {
          locked: false,
          contentBackgroundColor: '#ffffff',
        },
      },
      {
        id: uuidv4(),
        type: ContentComponentType.BLOCK,
        columns: [
          {
            id: uuidv4(),
            type: ContentComponentType.COLUMN,
            width: 2,
            contents: [
              {
                id: uuidv4(),
                type: ContentComponentType.TEXT,
                values: {
                  text: '<p>Sample text 1</p>',
                  fontFamily: 'Arial',
                  fontWeight: 'Regular',
                  fontSize: 14,
                  textColor: '#a2d6f9',
                  textAlign: 'left',
                  lineHeight: 120,
                  inheritBodyStyles: true,
                  linkColor: '#3aaee0',
                  underline: false,
                  containerPadding: {
                    paddingBottom: 10,
                    paddingTop: 10,
                    paddingLeft: 10,
                    paddingRight: 10,
                  },
                  displayConditions: [
                    EventType.Video,
                    EventType.Normal,
                  ],
                  locked: false,
                },
              },
              {
                id: uuidv4(),
                type: ContentComponentType.VARIABLE,
                values: {
                  value: '.event.location',
                  textAlign: 'center',
                  fontSize: 10,
                  lineHeight: 150,
                  textColor: '#fd5057',
                  locked: false,
                },
              },
              {
                id: uuidv4(),
                type: ContentComponentType.VARIABLE,
                values: {
                  value: '.event.startDate',
                  isDate: true,
                  textAlign: 'center',
                  fontSize: 32,
                  textColor: '#5c5c5c',
                  paddingTop: 20,
                  paddingRight: 30,
                  paddingBottom: 40,
                  paddingLeft: 30,
                  dateFormat: DateFormat.yyyyMMddhhmm,
                  lineHeight: 140,
                  displayConditions: [EventType.Normal, EventType.Video],
                  locked: false,
                },
              },
            ],
            values: {},
          },
          {
            id: uuidv4(),
            type: ContentComponentType.COLUMN,
            width: 1,
            contents: [
              {
                id: uuidv4(),
                type: ContentComponentType.TEXT,
                values: {
                  text: '<p>Sample text 2</p>',
                  fontFamily: 'Arial',
                  fontWeight: 'Regular',
                  fontSize: 20,
                  textColor: '#a2d6f9',
                  textAlign: 'left',
                  lineHeight: 120,
                  inheritBodyStyles: true,
                  linkColor: '#3aaee0',
                  underline: false,
                  containerPadding: {
                    paddingBottom: 10,
                    paddingTop: 10,
                    paddingLeft: 10,
                    paddingRight: 10,
                  },
                  displayConditions: [
                    EventType.Video,
                    EventType.Normal,
                  ],
                  locked: false,
                },
              },
              {
                id: uuidv4(),
                type: ContentComponentType.HEAD,
                values: {
                  text: '<p>Sample head 3</p>',
                  headingType: HeadingType.H3,
                  fontFamily: 'Arial',
                  fontWeight: 'Regular',
                  fontSize: 20,
                  textColor: '#a2d6f9',
                  textAlign: 'left',
                  lineHeight: 120,
                  inheritBodyStyles: true,
                  linkColor: '#3aaee0',
                  underline: false,
                  containerPadding: {
                    paddingBottom: 10,
                    paddingTop: 10,
                    paddingLeft: 10,
                    paddingRight: 10,
                  },
                  locked: false,
                },
              },
            ],
            values: {},
          },
          {
            id: uuidv4(),
            type: ContentComponentType.COLUMN,
            width: 1,
            contents: [
              {
                id: uuidv4(),
                type: ContentComponentType.HTML,
                values: {
                  htmlContent: '<div>Sample html 1</div>',
                  containerPadding: {
                    paddingBottom: 10,
                    paddingTop: 10,
                    paddingLeft: 10,
                    paddingRight: 10,
                  },
                  locked: false,
                },
              },
            ],
            values: {},
          },
        ],
        values: {
          displayConditions: [EventType.Normal, EventType.Video],
          contentBackgroundColor: '#ffffff',
          backgroundImageUrl: 'https://cdn.templates.unlayer.com/assets/1606924485372-1.jpg',
          locked: false,
          backgroundPosition: BackgroundPosition.TOP_LEFT,
        },
      },
    ],
    values: {
      textColor: '#2c2c2c',
      backgroundColor: '#E8D4BB',
      contentAlignment: 'center',
      contentWidth: 600,
      fontFamily: 'Arial',
      linkColor: '#0000EE',
      underline: false,
    },
  },
};

export const exampleComponent: IRow = {
  id: uuidv4(),
  type: ContentComponentType.BLOCK,
  columns: [
    {
      id: uuidv4(),
      type: ContentComponentType.COLUMN,
      width: 1,
      contents: [
        {
          id: uuidv4(),
          type: ContentComponentType.MENU,
          values: {
            menuItems: [
              {
                id: uuidv4(),
                text: 'Just text',
                href: '',
                name: '',
                target: '_self',
                actionType: SiteAction.WEBSITE,
              },
              {
                id: uuidv4(),
                text: 'Link text',
                href: 'https://telex.hu',
                name: '',
                target: '_self',
                actionType: SiteAction.WEBSITE,
              },
              {
                id: uuidv4(),
                text: 'Just text again',
                href: '',
                name: '',
                target: '_self',
                actionType: SiteAction.WEBSITE,
              },
            ],
            fontSize: 16,
            fontFamily: 'Arial',
            fontWeight: 'Regular',
            linkColor: '#5c5c5c',
            textColor: '#2c2c2c',
            layout: 'horizontal',
            separator: '|',
            textAlign: 'right',
            paddingTop: 10,
            paddingBottom: 10,
            paddingRight: 10,
            paddingLeft: 10,
            containerPadding: {
              paddingTop: 10,
              paddingBottom: 10,
              paddingRight: 10,
              paddingLeft: 10,
            },
            locked: false,
          },
        },
      ],
      values: {},
    },
    {
      id: uuidv4(),
      type: ContentComponentType.COLUMN,
      width: 1,
      contents: [
        {
          id: uuidv4(),
          type: ContentComponentType.TEXT,
          values: {
            text: '<p>Lorem ipsum dolor imet</p>',
            fontFamily: 'Arial',
            fontWeight: 'Regular',
            fontSize: 14,
            textColor: '#61a71b',
            textAlign: 'center',
            lineHeight: 120,
            inheritBodyStyles: true,
            linkColor: '#3aaee0',
            underline: false,
            containerPadding: {
              paddingBottom: 10,
              paddingTop: 10,
              paddingLeft: 10,
              paddingRight: 10,
            },
            displayConditions: [
              EventType.Video,
              EventType.Normal,
            ],
            locked: false,
          },
        },
      ],
      values: {},
    },
  ],
  values: {
    locked: false,
    contentBackgroundColor: '#ffffff',
  },
};
